unbind C-b
set -g status off

set -g default-shell "/run/current-system/sw/bin/bash"
set -g default-command "/run/current-system/sw/bin/bash --login -i"

# ctrl+, → next pane
bind -n C-\, select-pane -t :.+

# ctrl+. → zoom toggle
bind -n C-\. resize-pane -Z

bind -n M-\, split-window -h
bind -n M-\. split-window -v

# resize
bind -n S-M-Left resize-pane -L 5
bind -n S-M-Right resize-pane -R 5

# bind -n C-1 select-window -t 1
# bind -n C-2 if-shell "tmux select-window -t 2" "" "new-window -t 2"
# bind -n C-3 if-shell "tmux select-window -t 3" "" "new-window -t 3"
# bind -n C-4 if-shell "tmux select-window -t 4" "" "new-window -t 4"
