# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-b9853b29-34cd-4b17-8482-9d74e95d66fe";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-b9853b29-34cd-4b17-8482-9d74e95d66fe".device = "/dev/disk/by-uuid/b9853b29-34cd-4b17-8482-9d74e95d66fe";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/746A-0C4E";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-b02eb1dd-3283-4e78-aec9-7f82948c551c";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
